### ISSUE TITLE
neutron rbac request failed

### ISSUE THREAD

**Issue by stelucz** [Juniper/contrail-neutron-plugin#93]
Trying to create neutron rbac
Command:
```
openstack network rbac create --target-project d15e9ad42810461db9681f32d6751f7d --action access_as_shared --type network 6af1d2f8-2d3f-4695-a2bf-6a81e6649b46
```

Output:
```
HttpException: Internal Server Error, Request Failed: internal server error while processing your request.
```

Neutron-server log:
```
08:04:11.688 1789 ERROR neutron.api.v2.resource [req-f8ad3780-18df-4030-8a66-063339bf0aed 7d326bdb37b44a21812f8d2ee21a8f00 ec1965ade7434221b21415525a2bcc45 - - -] create failed: No details. │
08:04:11.688 1789 ERROR neutron.api.v2.resource Traceback (most recent call last): │
08:04:11.688 1789 ERROR neutron.api.v2.resource File "/usr/lib/python2.7/dist-packages/neutron/api/v2/resource.py", line 93, in resource │
08:04:11.688 1789 ERROR neutron.api.v2.resource result = method(request=request, **args) │
08:04:11.688 1789 ERROR neutron.api.v2.resource File "/usr/lib/python2.7/dist-packages/neutron/api/v2/base.py", line 436, in create │
08:04:11.688 1789 ERROR neutron.api.v2.resource return self._create(request, body, **kwargs) │
08:04:11.688 1789 ERROR neutron.api.v2.resource File "/usr/lib/python2.7/dist-packages/neutron/db/api.py", line 95, in wrapped │
08:04:11.688 1789 ERROR neutron.api.v2.resource setattr(e, '_RETRY_EXCEEDED', True) │
08:04:11.688 1789 ERROR neutron.api.v2.resource File "/usr/lib/python2.7/dist-packages/oslo_utils/excutils.py", line 220, in __exit__ │
08:04:11.688 1789 ERROR neutron.api.v2.resource self.force_reraise() │
08:04:11.688 1789 ERROR neutron.api.v2.resource File "/usr/lib/python2.7/dist-packages/oslo_utils/excutils.py", line 196, in force_reraise │
08:04:11.688 1789 ERROR neutron.api.v2.resource six.reraise(self.type_, self.value, self.tb) │
08:04:11.688 1789 ERROR neutron.api.v2.resource File "/usr/lib/python2.7/dist-packages/neutron/db/api.py", line 91, in wrapped │
08:04:11.688 1789 ERROR neutron.api.v2.resource return f(*args, **kwargs) │
08:04:11.688 1789 ERROR neutron.api.v2.resource File "/usr/lib/python2.7/dist-packages/oslo_db/api.py", line 151, in wrapper │
08:04:11.688 1789 ERROR neutron.api.v2.resource ectxt.value = e.inner_exc │
08:04:11.688 1789 ERROR neutron.api.v2.resource File "/usr/lib/python2.7/dist-packages/oslo_utils/excutils.py", line 220, in __exit__ │
08:04:11.688 1789 ERROR neutron.api.v2.resource self.force_reraise() │
08:04:11.688 1789 ERROR neutron.api.v2.resource File "/usr/lib/python2.7/dist-packages/oslo_utils/excutils.py", line 196, in force_reraise │
08:04:11.688 1789 ERROR neutron.api.v2.resource six.reraise(self.type_, self.value, self.tb) │
08:04:11.688 1789 ERROR neutron.api.v2.resource File "/usr/lib/python2.7/dist-packages/oslo_db/api.py", line 139, in wrapper │
08:04:11.688 1789 ERROR neutron.api.v2.resource return f(*args, **kwargs) │
08:04:11.688 1789 ERROR neutron.api.v2.resource File "/usr/lib/python2.7/dist-packages/neutron/db/api.py", line 131, in wrapped │
08:04:11.688 1789 ERROR neutron.api.v2.resource traceback.format_exc()) │
08:04:11.688 1789 ERROR neutron.api.v2.resource File "/usr/lib/python2.7/dist-packages/oslo_utils/excutils.py", line 220, in __exit__ │
08:04:11.688 1789 ERROR neutron.api.v2.resource self.force_reraise() │
08:04:11.688 1789 ERROR neutron.api.v2.resource File "/usr/lib/python2.7/dist-packages/oslo_utils/excutils.py", line 196, in force_reraise │
08:04:11.688 1789 ERROR neutron.api.v2.resource six.reraise(self.type_, self.value, self.tb) │
08:04:11.688 1789 ERROR neutron.api.v2.resource File "/usr/lib/python2.7/dist-packages/neutron/db/api.py", line 126, in wrapped │
08:04:11.688 1789 ERROR neutron.api.v2.resource return f(*dup_args, **dup_kwargs) │
08:04:11.688 1789 ERROR neutron.api.v2.resource File "/usr/lib/python2.7/dist-packages/neutron/api/v2/base.py", line 549, in _create │
08:04:11.688 1789 ERROR neutron.api.v2.resource obj = do_create(body) │
08:04:11.688 1789 ERROR neutron.api.v2.resource File "/usr/lib/python2.7/dist-packages/neutron/api/v2/base.py", line 512, in do_create │
08:04:11.688 1789 ERROR neutron.api.v2.resource obj_creator = getattr(self._plugin, action) │
08:04:11.688 1789 ERROR neutron.api.v2.resource AttributeError: 'NeutronPluginContrailCoreV2' object has no attribute 'create_rbac_policy' │
08:04:11.688 1789 ERROR neutron.api.v2.resource
```

OpenStack Ocata and OpenContrail 3.1.1.1

**Comment by shafiqmomin** [comment]
did you got solution for this

**Comment by stelucz** [comment]
@shafiqmomin No, Juniper killed Open/Contrail.
